### ISSUE TITLE
Is it possible to make checksum optional for the https:// urls?

### ISSUE THREAD

**Issue by virtuman** [chef-cookbooks/remote_install#9]
Is it possible to make checksum optional for the https:// urls or are you opposed to that idea?

**Comment by iennae** [comment]
@virtuman As documented in the readme this is a highly opinionated cookbook that is used by the Chef Release Engineering team. Ensuring that there is a checksum to verify against helps to prevent man in the middle attacks when downloading a remote file. It is unlikely that we would make the checksum optional for this cookbook.
